# command line: /home/jerry/STGCN/demo.py

config: /home/jerry/STGCN/model/demo.yaml
device:
- 0
ignore_weights: []
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: mediapipe_49
        strategy: spatial
    in_channels: 2
    num_class: 7
print_log: true
save_log: true
use_gpu: true
weights: /home/jerry/STGCN/model/epoch50_model.pt
work_dir: ./work_dir/tmp
